from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response


class PromptView(APIView):
    def post(self, request):
        # prompt = request.data.get('prompt')
        # TODO: Use the prompt to generate a poem using
        poem = 'This is a sample poem generated by the AI algorithm'

        return Response({'poem': "This is your response poem "})
