import os

from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response


import openai
# from config import OPEN_AI_API_KEY

from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

OPEN_AI_API_KEY = os.environ['OPEN_AI_API_KEY']

openai.api_key = OPEN_AI_API_KEY

class PromptView(APIView):
    def post(self, request):
        # prompt = request.data.get('prompt')
        # TODO: Use the prompt to generate a poem using
        # poem = 'This is a sample poem generated by the AI algorithm'

        print(request.data.get('prompt'))
        print(request.data.get('theme'))
        print(request.data.get('stanzas'))
        print(request.data.get('verses'))


        final_prompt = "A poem  about " + request.data.get('prompt') +\
                        ", theme is "+ request.data.get('theme') + " with " + request.data.get('stanzas')+\
                        " stanzas and " + request.data.get('verses') + " verses"
        # final_prompt = "a poem " + request.data.get('stanzas') + "stanzas with " +  request.data.get('verses') + " verses " + "" \
        #                 "about " + request.data.get('theme') + "and " +request.data.get('prompt') +" is :"

        print(final_prompt)

        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": final_prompt}]
        )

        image_response = openai.Image.create(
            prompt=request.data.get('theme') + " and " + request.data.get('prompt'),
            n=1,
            size="1024x1024"
        )

        print(image_response['data'][0]['url'])
        # print(response.choices[0].message.content)
        # print(response.choices[0].message)
        # print(response.choices[0])
        # print(response)


        return Response(
            {'poem': response.choices[0].message.content,
             "image": image_response['data'][0]['url']
             }

        )
